version: '3'

services:
  postgres:
    image: postgres:14-alpine
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - 5433:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./init-sql:/docker-entrypoint-initdb.d
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_INITDB_ARGS: "--encoding UTF8 --no-locale"

volumes:
  db-store:
