version: '3'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5433:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./init-sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_INITDB_ARGS: "--encoding UTF8 --no-locale"

volumes:
  db-store:
